version: "3.9"

services:
  app:
    image: hardening-lab/app:1.0.0
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - internal
    secrets:
      - source: db_password
        uid: "10001"
        gid: "10001"
        mode: 0400
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 64M
    read_only: true
    tmpfs:
      - /tmp:size=10M,noexec,nosuid,nodev

  falco:
    image: falcosecurity/falco:0.38.1
    networks:
      - internal
    privileged: true
    volumes:
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /lib/modules:/host/lib/modules:ro
      - /etc:/host/etc:ro
      - falco-rules:/etc/falco/rules.d:ro
      - falco-config:/etc/falco/falco.yaml:ro
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.20"
          memory: 256M

networks:
  internal:
    driver: overlay
    driver_opts:
      encrypted: "true"

volumes:
  falco-rules:
    external: true
  falco-config:
    external: true

secrets:
  db_password:
    external: true
